[build]
  # This command will be run in the root directory
  command = "cd client && npm install && npm run build"
  # The directory that contains the built client-side assets
  publish = "client/build"
  # The directory where our serverless functions are located
  functions = "netlify/functions"

[dev]
  # When running `netlify dev`, this will be the command to start the client dev server
  command = "cd client && npm start"
  # The port for the client dev server
  port = 3000
  # The directory for the client-side code
  publish = "client/build"

[[redirects]]
  # Proxy all API requests to our serverless function
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
